import { test, expect } from '@playwright/test';
test.use({ serviceWorkers: 'block' });
test('대표 스타호핑 코스 → 실제 이정표 → 완료 → 기록 → 진도 복원', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-06T12:00:00Z'));
  await page.goto('#/learn?section=courses');
  await expect(page.getByTestId('course-themes').getByRole('button')).toHaveCount(3);
  await page.getByTestId('course-theme-telescope').click();
  await page.getByTestId('course-group-starhop').click();
  await expect(page.getByTestId('hop-courses').getByRole('button')).toHaveCount(6);
  await page.getByTestId('course-hercules-keystone').click();
  await expect(page.getByTestId('hop-course-detail')).toBeVisible();
  await expect(page.getByRole('button', { name: '관측 기록 쓰기' })).toBeDisabled();
  await page.screenshot({ path: 'tests/e2e/__screenshots__/hop-course-detail.png' });
  await page.getByRole('button', { name: '스타호핑 시작', exact: true }).click();
  await expect(page.getByTestId('starhop')).toContainText('허큘리스');
  await expect(page.getByTestId('hop-step')).toHaveCount(1);
  await page.getByRole('button', { name: '출발 별을 시야 중앙에 놓았어요' }).click();
  await page.getByTestId('hop-confirm').click();
  await page.getByTestId('hop-finish').click();
  await page.getByRole('button', { name: '관측 코스로 돌아가기' }).click();
  await expect(page.getByTestId('hop-course-progress')).toContainText('✓ 차트를');
  await page.getByRole('button', { name: '관측 기록 쓰기' }).click();
  await page.getByTestId('obs-notes').fill('에타별에서 M13까지 별을 이어 찾았어요.');
  await page.getByTestId('obs-save').click();
  await expect(page.getByTestId('observation-form')).toHaveCount(0);
  await page.reload();
  await expect(page.getByTestId('hop-course-progress')).toContainText('✓ 찾은 모습');
  await page.goto('#/learn?section=courses');
  await expect(page.getByTestId('course-themes').getByRole('button')).toHaveCount(3);
  await page.getByTestId('course-theme-telescope').click();
  await page.getByTestId('course-group-starhop').click();
  await expect(page.getByTestId('course-hercules-keystone')).toContainText('2/2');
  await expect(page.getByTestId('course-andromeda-chain')).toContainText('0/2');
});
