import type { LocalizedText } from './historyQuests';

type StoryChapter = { title: LocalizedText; bridges: [LocalizedText, LocalizedText] };
const chapter = (
  ko: string,
  en: string,
  secondKo: string,
  secondEn: string,
  thirdKo: string,
  thirdEn: string,
): StoryChapter => ({
  title: { ko, en },
  bridges: [
    { ko: secondKo, en: secondEn },
    { ko: thirdKo, en: thirdEn },
  ],
});

// 같은 발견을 관측 → 관계 확인 → 적용으로 잇는다. 채점 문항·수치·저장 ID는 바꾸지 않는다.
export const HISTORY_STORY: Record<string, StoryChapter> = {
  'eratosthenes-circumference': chapter(
    '그림자로 잰 둥근 땅',
    'A round Earth, measured by shadows',
    '머리 위 방향이 다르면 그림자의 각도도 달라진다. 이제 그 각도가 지구 한 바퀴 중 얼마에 해당하는지 연결해 보자.',
    'Different upright directions give different shadow angles. Connect that angle to a fraction of a full turn around Earth.',
    '각도와 땅 위의 거리를 같은 비율로 묶을 수 있다. 두 도시에서 얻은 숫자로 지구 한 바퀴를 계산해 보자.',
    'Angle and ground distance follow the same proportion. Use the measurements from two cities to work out a full circumference.',
  ),
  'eratosthenes-uncertainty': chapter(
    '숫자는 얼마나 믿을 만할까',
    'How much can we trust the number?',
    '거리도 각도도 조금씩 흔들린다. 서로 독립인 두 흔들림을 한 결과에 모으는 방법을 생각해 보자.',
    'Both distance and angle vary a little. Consider how two independent uncertainties combine in one result.',
    '각 측정의 흔들림을 알았다. 이번에는 구한 둘레에 어느 정도 불확실성이 따라오는지 계산해 보자.',
    'With the uncertainty of each measurement in hand, work out how uncertain the circumference is.',
  ),
  'eratosthenes-baseline': chapter(
    '비스듬한 두 도시',
    'Two cities on a slant',
    '그림자가 비교하는 것은 남북 간격이다. 비스듬한 길에서 그 간격만 꺼내 보자.',
    'The shadows compare north–south separation. Extract that part from a slanted route.',
    '지도에서 잰 길과 그림자가 알려 준 간격이 다르다. 둘을 구별하지 않으면 계산이 어느 쪽으로 틀어질까?',
    'The mapped route and the separation measured by shadows differ. Which way does using the wrong one shift the result?',
  ),
  'kepler-binary-mass': chapter(
    '두 별을 재는 저울',
    'Weighing a pair of stars',
    '두 별 사이 궤도의 크기를 정했다. 같은 시간에 더 큰 궤도를 돌게 하려면 질량은 어떻게 달라져야 할까?',
    'We have the size of the relative orbit. How must mass change to complete a larger orbit in the same time?',
    '이제 궤도의 크기와 주기를 함께 넣어, 두 별의 총질량을 구해 보자.',
    'Now combine orbit size and period to find the total mass of the pair.',
  ),
  'kepler-apsis-speed': chapter(
    '가까워지면 빨라지는 이유',
    'Why closer means faster',
    '원이 타원으로 바뀌면 가까운 곳과 먼 곳이 생긴다. 두 지점의 거리와 속력을 짝지어 보자.',
    'An ellipse has a nearest and a farthest point. Pair the distance with the speed at each end.',
    '가까운 곳에서는 빨라지고 먼 곳에서는 느려진다. 주어진 타원에서 그 속력의 비를 계산해 보자.',
    'Faster near the star, slower far away: calculate that speed ratio for the given ellipse.',
  ),
  'kepler-flight-time': chapter(
    '타원 위의 시계',
    'A clock along the ellipse',
    '보조 원 위의 각도를 읽었다. 이제 시간과 일정하게 나란히 흐르는 각도를 생각해 보자.',
    'We have an angle on the auxiliary circle. Now consider the angle that advances uniformly with time.',
    '두 각도를 연결하면 타원 위의 위치를 시간으로 바꿀 수 있다. 출발점에서 여기까지 얼마나 걸렸을까?',
    'Connecting the two angles turns orbital position into elapsed time. How long has the journey taken?',
  ),
  'romer-path-speed': chapter(
    '빛이 오는 데 걸린 시간',
    'The time light takes to arrive',
    '늦게 도착한 만큼 빛이 더 멀리 왔다. 길이와 시간을 어떤 단위로 맞춰야 속력을 얻을까?',
    'The extra delay comes with extra distance. Which units let us turn them into a speed?',
    '이오가 보내온 시각의 차이를 빛의 여행 시간으로 읽어 보자. 경로와 지연을 함께 계산할 차례다.',
    'Read the timing difference from Io as extra travel time. Put the added path length and delay together.',
  ),
  'romer-period-bias': chapter(
    '한 번씩 쌓이는 지연',
    'A delay that builds each orbit',
    '사건 수와 사이 간격 수를 구별했다. 각 간격에 작은 여행 시간이 더해지면 시계는 어떻게 보일까?',
    'We have counted intervals rather than events. How does the clock look when each interval gains a little travel time?',
    '작은 지연이 여러 주기 동안 쌓였다. 한 주기에서 길어진 시간을 되짚어 보자.',
    'A small delay has accumulated over many periods. Work back to the added time per period.',
  ),
  'romer-model-test': chapter(
    '다음 계절에도 맞을까',
    'Will it predict the next season?',
    '설명을 고르려면 서로 다른 예측을 찾아야 한다. 먼저 주기 자체를 잘못 잡았을 때의 흔적을 보자.',
    'To choose between explanations, look for different predictions. First trace what a mistaken period would leave behind.',
    '주기 오류의 흔적과 빛의 여행이 바뀌는 흔적을 비교했다. 어느 관측이 둘을 더 잘 가려낼까?',
    'Compare a period error with changing light travel time. Which observation best separates them?',
  ),
  'leavitt-modulus': chapter(
    '깜빡임에서 거리까지',
    'From a pulse to a distance',
    '별 자체의 밝기와 우리가 받은 밝기를 구별했다. 둘의 차이를 거리로 바꾸려면 로그를 거꾸로 읽어야 한다.',
    'We have separated intrinsic brightness from received light. Turning their difference into distance means undoing a logarithm.',
    '주기로 별의 밝기를 짐작하고, 먼지 영향을 뺀 뒤 거리를 찾는다. 이 별의 관측값으로 이어가 보자.',
    'Use the period to estimate brightness, correct for dust, then find the distance from this star’s measurements.',
  ),
  'leavitt-extinction-bias': chapter(
    '먼지가 바꾼 거리',
    'A distance distorted by dust',
    '먼지의 영향은 등급에서 뺀다. 두 거리의 로그 차이를 비교하려면 어떤 관계가 필요할까?',
    'We subtract the dust contribution from magnitude. What relation helps compare the logarithms of two distances?',
    '먼지 때문에 잃은 빛을 거리 탓으로 돌렸다. 그 실수가 거리를 얼마나 늘리는지 구해 보자.',
    'We blamed the light lost to dust on distance. Work out how much that stretches the estimate.',
  ),
  'leavitt-zero-point': chapter(
    '거리 눈금의 시작점',
    'Where the distance scale starts',
    '패턴의 기울기는 거리 눈금이 바뀌어도 남는다. 하지만 실제 거리를 붙일 기준은 따로 필요하다.',
    'The slope survives a shift of the distance scale, but assigning a real distance still needs an anchor.',
    '같은 거리에 놓인 별들이 알려 주는 것과 알려 주지 않는 것을 구별해 보자.',
    'Separate what stars at a shared distance can tell us from what still needs another measurement.',
  ),
  'payne-saha-ratio': chapter(
    '뜨거운 수소의 전자',
    'Electrons in hot hydrogen',
    '전자를 잃는 과정이 이온화다. 온도가 오를 때 에너지 장벽을 넘는 비율은 어떻게 달라질까?',
    'Losing an electron is ionization. How does rising temperature change the factor describing an energy barrier?',
    '온도는 거듭제곱 항과 지수 항에 함께 들어간다. 두 층에서 이온화 비가 얼마나 달라지는지 계산해 보자.',
    'Temperature enters both a power and an exponential. Calculate how the ionization ratio changes between the two layers.',
  ),
  'payne-level-population': chapter(
    '선을 만드는 수소의 몫',
    'The fraction that makes a line',
    '중성이어야 하고, 그중 알맞은 준위에 있어야 한다. 먼저 전체에서 중성 수소가 차지하는 몫을 찾아보자.',
    'An atom must be neutral and in the right level. First find the fraction of all hydrogen that is neutral.',
    '두 조건의 비율을 곱하면 선을 만들 수 있는 원자의 몫이 나온다. 서로 다른 두 층을 비교해 보자.',
    'Multiplying the two fractions gives the population able to make the line. Compare the two layers.',
  ),
  'payne-abundance-inference': chapter(
    '선의 깊이만으로 알 수 있을까',
    'Can line depth tell the whole story?',
    '통과한 빛은 원자의 수만으로 정해지지 않는다. 같은 선을 만드는 서로 다른 원인을 가려 보자.',
    'Transmitted light depends on more than atom counts. Look for a way to distinguish different causes of the same line.',
    '온도와 입자 상태, 빛의 전달을 함께 생각했다. 이제 두 별의 조성을 비교할 분석을 골라 보자.',
    'With temperature, particle populations and light transfer in mind, choose an analysis for comparing the stars’ compositions.',
  ),
  'einstein-deflection': chapter(
    '태양 곁을 지나는 빛',
    'Light passing the Sun',
    '빛이 태양 중심에서 얼마나 떨어져 지나는지 정했다. 더 멀리 지나면 휨은 어떻게 바뀔까?',
    'We have defined the distance of the light path from the Sun’s center. How does passing farther away change the bending?',
    '거리와 편향각의 관계를 실제 수치에 적용해 보자. 사진에서 잴 수 있는 초각으로 답을 바꾼다.',
    'Apply the distance–deflection relation to the numbers, then convert to arcseconds that can be measured in a photograph.',
  ),
  'einstein-weighted-fit': chapter(
    '두 관측팀의 숫자',
    'Two teams, two measurements',
    '더 정밀한 측정에 더 큰 무게를 준다. 불확실성이 줄어드는 만큼 가중치는 얼마나 커질까?',
    'A more precise measurement gets more weight. How fast does that weight grow as uncertainty shrinks?',
    '두 팀의 정밀도를 반영해 하나의 추정값으로 모아 보자.',
    'Combine the two measurements into one estimate while respecting their different precision.',
  ),
  'einstein-systematics': chapter(
    '사진판 전체의 흔들림',
    'A shift across the whole plate',
    '같은 자의 오류는 반복해도 남는다. 반대로 서로 독립인 흔들림만 있다면 평균은 얼마나 안정될까?',
    'An error in the same ruler survives repetition. How much steadier does averaging become when only independent noise remains?',
    '별마다 다른 오차와 사진판 전체의 공통 오차를 따로 보았다. 별을 많이 재도 남는 불확실성은 무엇일까?',
    'Separate star-by-star errors from a shared plate error. What uncertainty remains even after measuring many stars?',
  ),
  'chandra-composition': chapter(
    '별을 받치는 전자의 수',
    'Counting the electrons that support a star',
    '전자 축퇴압이 중력에 맞선다. 같은 질량이라도 조성이 달라지면 지지에 참여할 전자 수가 달라진다.',
    'Electron degeneracy pressure resists gravity. A different composition changes how many electrons are available per unit mass.',
    '전자 하나당 질량을 알면 이 이상화된 별의 질량 한계를 구할 수 있다.',
    'The mass per electron lets us calculate the mass limit of this idealized star.',
  ),
  'chandra-radius': chapter(
    '무거워질수록 작아지는 별',
    'A heavier star can be smaller',
    '음의 지수는 양이 늘 때 결과가 줄어드는 관계다. 반지름 식에 나오는 세제곱근과 역수를 차례로 읽어 보자.',
    'A negative power can make the result shrink as its input grows. Read the cube root and reciprocal in the radius relation in order.',
    '같은 조성의 두 별에서 질량만 바뀌었다. 반지름은 원래의 얼마가 될까?',
    'Only mass changes between these two models of the same composition. What fraction of the original radius remains?',
  ),
  'chandra-scaling': chapter(
    '수축으로도 이길 수 없다면',
    'When shrinking cannot win',
    '압력은 중력이 요구하는 크기를 따라가야 한다. 별이 작아질 때 거듭제곱이 어떻게 합쳐지는지 살펴보자.',
    'Pressure must keep up with gravity’s demand. Examine how powers combine as the star shrinks.',
    '두 압력이 반지름에 똑같이 의존한다면 수축만으로 균형을 되찾을 수 없다. 식에서 그 이유를 찾아보자.',
    'If both pressures depend on radius in the same way, shrinking alone cannot restore balance. Find that pattern in the equations.',
  ),
  'hubble-slope': chapter(
    '점들을 잇는 기울기',
    'A slope through the points',
    '예측에서 벗어난 양을 잔차로 읽었다. 양수와 음수가 서로 지워지지 않도록 직선을 평가해 보자.',
    'We have read deviations as residuals. Judge a line without letting positive and negative deviations cancel.',
    '점 세 개를 함께 설명하는 기울기를 찾아, 이 거리–속도 표에서 팽창의 척도를 구해 보자.',
    'Find the slope that describes all three points and read an expansion scale from the distance–velocity table.',
  ),
  'hubble-time': chapter(
    '팽창률을 시계로 바꾸기',
    'Turning expansion into a clock',
    '거리당 속도의 역수는 시간 차원이다. 초로 얻은 시간을 큰 우주 시간 단위로 옮길 준비를 하자.',
    'The inverse of velocity per distance has units of time. Prepare to convert seconds into a cosmic timescale.',
    '단위를 맞춘 뒤 역수를 계산한다. 이것은 오늘의 팽창률이 주는 시간 척도라는 점을 기억하자.',
    'Match the units and take the inverse. Keep in mind that this is a timescale from today’s expansion rate.',
  ),
  'hubble-calibration': chapter(
    '거리 자의 눈금이 바뀌면',
    'When the distance ruler changes',
    '점들이 가로로 늘어났다. 기울기를 구하는 식의 위아래에서 거리 눈금이 각각 몇 번 들어갈까?',
    'The points have stretched horizontally. Count how many distance factors enter the numerator and denominator of the slope.',
    '거리 눈금의 변화가 기울기를 바꾸고, 그 역수인 시간도 바꾼다. 두 결과를 함께 추적해 보자.',
    'The new distance scale changes the slope and its inverse timescale. Follow both changes together.',
  ),
  'zwicky-virial-mass': chapter(
    '빠른 은하들을 붙잡는 질량',
    'The mass holding fast galaxies together',
    '은하단 전체의 이동을 빼고 내부의 퍼짐을 보았다. 시선 한 방향에서 잰 값을 세 방향의 운동으로 이어 보자.',
    'We removed bulk motion to see the internal spread. Connect one line-of-sight measurement to motion in three directions.',
    '운동 에너지와 묶어 두는 중력이 균형을 이룬다고 가정하자. 이 모형에서 필요한 질량은 얼마일까?',
    'Assume kinetic energy and binding gravity satisfy virial equilibrium. How much mass does this model require?',
  ),
  'zwicky-noise-correction': chapter(
    '장비가 더한 흔들림',
    'The spread added by the instrument',
    '독립인 흔들림은 표준편차 대신 분산으로 더한다. 관측값에서 장비의 몫을 되돌려 빼 보자.',
    'Independent contributions add as variances, not standard deviations. Undo the instrument’s contribution to the observation.',
    '실제 운동의 퍼짐을 되찾았다. 같은 은하단 모형에서 질량 추정은 얼마나 줄어들까?',
    'We have recovered the spread of real motion. How much does the mass estimate fall in the same cluster model?',
  ),
  'zwicky-evidence': chapter(
    '발견 앞에서 한 번 더 점검',
    'Checking a surprising discovery',
    '별빛에 빠진 보통 물질도 장부에 넣어야 한다. 운동과는 다른 방법으로 질량을 확인할 수 있을까?',
    'Ordinary matter missing from the starlight estimate belongs in the ledger too. Can a different method check the mass?',
    '물질의 장부와 모형의 가정을 점검했다. 현재 관측으로 말할 수 있는 결론을 골라 보자.',
    'With the matter inventory and model assumptions checked, choose a conclusion the observations can support.',
  ),
  'rubin-inclined-mass': chapter(
    '기울어진 은하를 바로 읽기',
    'Reading a tilted galaxy',
    '우리에게 보이는 속력은 회전의 일부다. 바로잡은 속력이 질량 식에서 얼마나 크게 반영되는지 보자.',
    'The speed we see is only part of the rotation. See how strongly the corrected speed enters the mass relation.',
    '먼저 기울기를 보정하고 그다음 질량을 구한다. 두 단계를 같은 관측값에 적용해 보자.',
    'First correct for inclination, then find the mass. Apply both steps to the same observation.',
  ),
  'rubin-density-slope': chapter(
    '총질량에서 밀도로',
    'From enclosed mass to density',
    '안에 든 질량과 그 자리의 밀도를 구별했다. 바깥으로 한 겹 더할 때 그 껍질의 크기는 어떻게 변할까?',
    'We distinguished enclosed mass from local density. How does a shell’s size change as we move outward?',
    '일정한 회전 속력이 요구하는 질량 증가를 얇은 껍질에 나눠 담아, 밀도의 변화를 구해 보자.',
    'Distribute the mass increase required by a flat rotation curve among thin shells to find how density changes.',
  ),
  'rubin-missing-fraction': chapter(
    '질량 장부에 없는 몫',
    'The part missing from the mass ledger',
    '속력의 비를 제곱해 질량의 비로 바꾼다. 설명한 몫에서 아직 남은 몫으로 넘어가 보자.',
    'Square the speed ratio to obtain a mass ratio. Move from the fraction explained to the fraction still missing.',
    '별과 기체가 설명하는 질량을 전체와 비교한다. 속력 차이가 아니라 질량의 비율로 답해 보자.',
    'Compare the mass explained by stars and gas with the total. Answer as a mass fraction, not a speed difference.',
  ),
};
